#!/bin/sh

name=$1
passwd=$2

function check_status() {
    if [ $? != 0 ]; then
        echo $1
        exit -1
    fi
}

openssl pkcs12 -export -in ${name}cert.pem -inkey ${name}key.pem -out ${name}.p12 -password "pass:${passwd}"
check_status "generate pkcs12 fail"

keytool -importkeystore -srckeystore ${name}.p12 -srcstorepass $passwd -srcstoretype PKCS12 -destkeystore ${name}.jks -deststorepass $passwd
check_status "generate keystore fail"

keytool -importcert -noprompt -trustcacerts -file rootcert.pem -keystore ${name}.jks -storepass $passwd -alias cacert
check_status "import cacert fail"

rm ${name}.p12
